### ISSUE TITLE
Add ability to log to different topics from the same logger instance.

### ISSUE THREAD

**Issue by lxe** [uber/kafka-logger#7]

**Comment by Raynos** [comment]
You can. Create multiple KafkaLogger instances that share a kafkaClient and add them to logtron.

**Comment by lxe** [comment]
@Raynos ah awesome. Didn't see this in the docs: https://github.com/uber/kafka-logger/blob/master/index.js#L56

**Comment by closedLoop** [comment]
please mark as closed
